alias pc='lintian --color auto -i  --pedantic -I *.changes'
alias trabajo='ssh agarrido@10.200.3.29 -v'
alias dreamhost='ssh -v agm@ballechin.dreamhost.com'
alias copiar_movies='scp movies.db agm@ballechin.dreamhost.com:/home/agm/mogaal.com/movies'
alias clonar_debian='gbp clone --verbose --all --pristine-tar'
alias tesis='cd /home/mogaal/universidad/Pasantias/libro-pasantias/usb-tesis/'
