if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# default editor
export EDITOR=vim

# Browser 
export BROWSER=firefox

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export PAGER=less
export LESS='-F -g -i -M -R -S -w -X -z-4'

# locales
export LANG=en_GB.UTF-8

# GPG (gpg-mailkeys)
export NAME='Alejandro Garrido Mota'
export MAIL='garridomota@gmail.com'
export GPG_TTY=$(tty) # Because of GPG-agent

# Debian packing
export DEBEMAIL='alejandro@debian.org'
export DEBFULLNAME='Alejandro Garrido Mota'
export QUILT_PATCHES=debian/patches
export DEBUILD_DPKG_BUILDPACKAGE_OPTS="-us -uc -sa -i -I"
export DEBSIGN_KEYID="F1C09EFB"

# Set history configuration
export HISTSIZE=1000
export HISTFILESIZE=2000
export HISTFILE=~/.zsh_history
export HISTCONTROL=ignoredups:erasedups

# Save and reload the history after each command finishes
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history"
export HH_CONFIG=hicolor

# Terminal colors, required also vim-lightline
export TERM=xterm-256color

# Golang
export GO111MODULE=on 

# KDE/Konsole Horrible bug: https://bugs.kde.org/show_bug.cgi?id=373232
export QT_SCREEN_SCALE_FACTORS=$_QT_SCREEN_SCALE_FACTORS

## pyenv configs
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# React Native
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi

# OSX

