# default editor
export EDITOR=nvim

# Browser 
export BROWSER=firefox

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export PAGER=less
export LESS='-F -g -i -M -R -S -w -X -z-4'

# locales
export LANG=en_GB.UTF-8

# GPG (gpg-mailkeys)
export NAME='Alejandro Garrido Mota'
export MAIL='garridomota@gmail.com'
export GPG_TTY=$(tty) # Because of GPG-agent

# Determine OS
if [ "$(uname)" = "Darwin" ]; then
  OS='mac'
elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
  OS='linux'
fi

# Architecture: my m1 uses arm and my desktop x86_64. Important because binaries are different
[[ $(uname -m) == arm* ]] && ARCH='arm'
[[ $(uname -m) == x86_64* ]] && ARCH='amd64'

# Debian packing
export DEBEMAIL='alejandro@debian.org'
export DEBFULLNAME='Alejandro Garrido Mota'
export QUILT_PATCHES=debian/patches
export DEBUILD_DPKG_BUILDPACKAGE_OPTS="-us -uc -sa -i -I"
export DEBSIGN_KEYID="F1C09EFB"

# Set history configuration
export HISTSIZE=1000
export HISTFILESIZE=2000
export HISTFILE=~/.zsh_history  # ensure history file visibility
export HISTCONTROL=ignoredups:erasedups

# Save and reload the history after each command finishes
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history"
export HH_CONFIG=hicolor

# Terminal colors, required also vim-lightline
export TERM=xterm-256color

# Golang
export GO111MODULE=on 

# KDE/Konsole Horrible bug: https://bugs.kde.org/show_bug.cgi?id=373232
export QT_SCREEN_SCALE_FACTORS=$_QT_SCREEN_SCALE_FACTORS

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Android Studio
if [[ "$OS" == "linux" ]]; then
  export ANDROID_HOME=$HOME/Android/Sdk
else # OSX
  export ANDROID_HOME=$HOME/Library/Android/sdk

fi
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
. "$HOME/.cargo/env"
