if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# default editor
export EDITOR=vim

# Browser 
export BROWSER=google-chrome

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export PAGER=less
export LESS='-F -g -i -M -R -S -w -X -z-4'

# locales
export LANG=en_GB.UTF-8

# GPG (gpg-mailkeys)
export NAME='Alejandro Garrido Mota'
export MAIL='garridomota@gmail.com'
export GPG_TTY=$(tty) # Because of GPG-agent

# Debian packing
export DEBEMAIL='alejandro@debian.org'
export DEBFULLNAME='Alejandro Garrido Mota'
export QUILT_PATCHES=debian/patches
export DEBUILD_DPKG_BUILDPACKAGE_OPTS="-us -uc -sa -i -I"
export DEBSIGN_KEYID="F1C09EFB"

# Set history configuration
export HISTSIZE=1000
export HISTFILESIZE=2000
export HISTFILE=~/.zsh_history
export HISTCONTROL=ignoredups:erasedups

# Save and reload the history after each command finishes
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history"
export HH_CONFIG=hicolor

# Only MacOS: brew tap sambadevi/powerlevel9k && brew install powerlevel9k 
#source /usr/local/opt/powerlevel9k/powerlevel9k.zsh-theme
#export POWERLEVEL9K_MODE='nerdfont-complete'

###########
## Work ###
###########

# k8s 
export KUBECONFIG=~/workspace/k8s/admin.conf
