# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load my aliases
if [[ -e "$HOME/.aliases" ]]; then
    source "$HOME/.aliases";
fi

# Load my functions
if [ -e "$HOME/dotfiles/zsh/functions" ]; then
  for function in $HOME/dotfiles/zsh/functions/*; do
    source $function
  done
fi

setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    incappendhistory  #Immediately append to the history file, not 
unsetopt  share_history

export HISTFILE=~/.zsh_history  # ensure history file visibility
export HH_CONFIG=hicolor        # get more colors
bindkey -s "\C-r" "\eqhh\n"     # bind hh to Ctrl-r (for Vi mode check doc)

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin:$HOME/Library/Python/3.7/bin"

# Add auto-completion for Kubernetes
if [ $commands[kubectl] ]; then source <(kubectl completion zsh); fi

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/Cellar/terraform/0.11.7/bin/terraform terraform

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mogaal/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/mogaal/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/mogaal/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/mogaal/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
