# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load my aliases
if [[ -e "$HOME/.aliases" ]]; then
    source "$HOME/.aliases";
fi
