# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load my aliases
if [[ -e "$HOME/.aliases" ]]; then
    source "$HOME/.aliases";
fi

# Load my functions
if [ -e "$HOME/dotfiles/zsh/functions" ]; then
  for function in $HOME/dotfiles/zsh/functions/*; do
    source $function
  done
fi

# Load my work envs
if [[ -e "$HOME/work/dotfiles/env" ]]; then
    source "$HOME/work/dotfiles/env";
fi

# Print a random, hopefully interesting, adage.
if (( $+commands[fortune] )); then
  if [[ -t 0 || -t 1 ]]; then
    fortune -s
    print
  fi
fi

setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    incappendhistory  #Immediately append to the history file, not 
unsetopt  share_history

if [ "$OS" = "linux" ]; then
  bindkey -s "\C-r" "\eqhstr\n"     # bind hh to Ctrl-r (for Vi mode check doc)
fi

if [ "$OS" = "mac" ]; then
  bindkey -s "\C-r" "\eqhh\n"     # bind hh to Ctrl-r (for Vi mode check doc)
fi

# Add auto-completion for Kubernetes
if [ $commands[kubectl] ]; then source <(kubectl completion zsh); fi

autoload -U +X bashcompinit && bashcompinit

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mogaal/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/mogaal/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/mogaal/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/mogaal/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

# RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# This is for direnv
eval "$(direnv hook zsh)"

## pyenv configs
if command -v pyenv 1>/dev/null 2>&1; then
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

eval "$(starship init zsh)" # startship
